spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:postgresql://localhost:5432/dbpitzeria
    username: postgres
    password: admcarlos
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

        hbm2ddl:
          auto: update
logging:
  level:
    org.springframework.security.web.*: debug

